version: '3.7'

services:
  app:
    env_file:
      - .env
    container_name: ${APP_NAME}_app
    restart: always
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    links:
      - mongo
    networks:
      - win_network
    depends_on:
      - mongo
  mongo:
    container_name: ${APP_NAME}_mongodb
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE=${DB_NAME}
    volumes:
      - .mongodb_data:/data/bd
    networks:
      - win_network

volumes:
  mongodb_data:
  
networks:
  win_network:
    driver: bridge
